runtime: java8
inbound_services:
- warmup
derived_file_type:
- java_precompiled
threadsafe: True
auto_id_policy: default
vpc_access_connector:
  name: projects/food-composer/locations/us-east1/connectors/gae-connector
api_version: 'user_defined'
handlers:
- url: /.*
  script: unused
  login: optional
  secure: optional
