CREATE TABLE IF NOT EXISTS m_station (
    id INT(11) NOT NULL AUTO_INCREMENT
    , station_cd VARCHAR(6) NOT NULL
    , station_nm VARCHAR(16) NOT NULL
    , line1_cd VARCHAR(6) NOT NULL
    , line2_cd VARCHAR(6) NOT NULL
    , line3_cd VARCHAR(6) NOT NULL
    , place_cd VARCHAR(6) NOT NULL
    , created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    , updated_at TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00'
    , PRIMARY KEY (id)
);
