CREATE TABLE IF NOT EXISTS t_news (
    id INT(11) NOT NULL AUTO_INCREMENT
    , news_category INT(2) NOT NULL
    , contents VARCHAR(4000) NOT NULL
    , regist_date TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00'
    , created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    , updated_at TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00'
    , PRIMARY KEY (id)
);
